### ISSUE TITLE
Password for 4.1 Crack?

### ISSUE THREAD

**Issue by unkn0wn-dev** [sinlee1/cobaltstrike_cracked#1]
There is a password required but none is provided.

**Comment by sinlee1** [comment]
@unkn0wn-dev This is not the English version. Are you sure you want to use it?

**Comment by unkn0wn-dev** [comment]
I mean if I have to, is there no English version?

**Comment by sinlee1** [comment]
I don't have any other version. You may need to Google it. @unkn0wn-dev

**Comment by ezal3103** [comment]
may you provide us with the zip password

**Comment by sinlee1** [comment]
@ezal3103 This is the modified Chinese version, are you sure you need it?

**Comment by ezal3103** [comment]
Yes, please.

**Comment by ezal3103** [comment]
Yes, please.

**Comment by sinlee1** [comment]
@ezal3103 Please send your email address

**Comment by ezal3103** [comment]
ez.altiar.com@gmail.com

**Comment by sinlee1** [comment]
@ezal3103 Packed and sent
